### ISSUE TITLE
替换我的模型后异常退出

### ISSUE THREAD

**Issue by simpsonyang** [ralph0813/Paddle_Lite_Object_Detection_Demo#3]
你好，我可以在手机上运行你的代码，但是当我用自己opt出来的模型替换了你的以后，运行到loading model就闪退了，网上查了一下，有可能是我的opt版本和paddlelite不一致的原因，请问你用的是哪个版本的opt，或者能否提供一下你用的opt，不胜感激。

**Comment by ralph0813** [comment]
具体的opt版本记不清了，应该是0.9或者0.8，本项目已经很久没更新了，建议参考新一些的教程。

**Comment by simpsonyang** [comment]
谢谢恢复，我已经确认不是opt版本和paddle lite版本的问题，而是inputTensor个数的问题，你的模型里面可能输入只有两个，（我用netron打不开你的模型文件），但是我的确实是3个，所以需要修改代码中这里：
// Set input shape
Tensor inputTensor1 = getInput(1);
inputTensor1.resize(inputShape);
Tensor sizeTensor = getInput(0);
sizeTensor.resize(new long[] {1,2});
Tensor scaleTensor = getInput(2);
scaleTensor.resize(new long[] {1,2});
然后运行不出错，并且找到了，但是坐标都是0，我调式了 outputTensor.getFloatData(), 里面的数值看起来和实际值确实不一样，这里就不知道改如何换算，还是怎么处理了。
